spring:
   data:
      mongodb:
         host: localhost
         port: 27017
         database: UserDetails

logging:
   level:
      org:
         springframework:
            data: debug 
server:
   port: 8102       
